server:
  port: 8888

spring:
  application:
    name: PveManagerBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/pve_manager
    username: pve_manager
    password: 12345678
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

proxmox:
  host: 10.3.2.11
  port: 8006
  username: root
  password: 12345678

jwt:
  secret: sOop-lwzVcoOV1_RE3yKFZ9QR4634T6zc9VLQ3rvZnk=


  logging:
    level:
      org:
        springframework:
          jdbc:
            core: debug
      hu:
        jandzsogyorgy: debug
      root: info
